### ISSUE TITLE
How to install? (Beginner to MooTools Plugins)

### ISSUE THREAD

**Issue by MichaelTunnell** [julesjanssen/chosen#15]
I have uploaded the css, min.js and the sprite to my server.

I've added the javascript call, css call in my code as well as edited the select form I want to change to class="chosen" but nothing happens.

I'm a designer with little JS knowledge so could you maybe hold my hand to explain how to install/activate this plugin?

I am trying to make it work with Joomla 1.5.x and i realize that platform uses 1.2 Mootools but I only want to use this on a few pages...so if anyone could help with that i would much appreciate it.

**Comment by RaphaelAudet** [comment]
You will need to write mootools javascript for this.

you will new to include mootools.js (http://mootools.net/)
try something like : 

```
window.addEvent('domready', function() {
  $$('.put-your-select-class-here').chosen();
});
```

**Comment by jonnsl** [comment]
take a look at the demo https://github.com/julesjanssen/chosen/blob/master/Demos/index.html
try to update to Joomla! 1.7 or 1.6 these versions use MooTools 1.3

**Comment by MichaelTunnell** [comment]
1.7 and 1.6 are Beta versions and are not solid releases even though they claim that they are which is why ALL developers still build for both.

I was hoping you might know how to update 1.5 to MT 1.3
