### ISSUE TITLE
opening a chosen select doesn't close other one

### ISSUE THREAD

**Issue by RaphaelAudet** [julesjanssen/chosen#16]
Hi

I got a case with 2 chosens selects : A and B. 
When clicking on B, the choices are displayed and I send an alert, requesting the user to fill in A first.

Usually clicking outside of B, the displayed options will collapse, but if I click on A, both chosen options are displayed.

Does someone else have this problem ?

Is there a "close" method I could use to force B to close?

Raphael

**Comment by RaphaelAudet** [comment]
ok I'm using a .results_hide(); in the mean time.

But still, opening a chosen picker should close the other open ones.

**Comment by jonnsl** [comment]
confirmed http://jsfiddle.net/rQ3ap/ it closes after a while  but it should close instantly
