### ISSUE TITLE
multiple > fireEvent('liszt:updated');

### ISSUE THREAD

**Issue by uffizi** [julesjanssen/chosen#18]
Hi
first - thanks for your work!

do you have an example with multiple-select and the fireEvent?
I don't get it to work, and by sending the form there is no post of the chosen selects..

thank you, c

**Comment by jonnsl** [comment]
Here is an example http://jsfiddle.net/rD8Fu/

**Comment by uffizi** [comment]
thank you.

but for an form, I still need to make a function to get the chosen as post-results?
or must it be with an ajax request?

sorry for not understanding.

Am 29.09.2011 um 23:39 schrieb Jonnathan:

**Comment by jonnsl** [comment]
just give a name to the select

```
<select name="multi_example">
<option value="1">Option 1</option>
<option value="2">Option 2</option>
</select>
```
