### ISSUE TITLE
disabled chosen

### ISSUE THREAD

**Issue by NKjoep** [julesjanssen/chosen#21]
Hello :)

would be useful to have the possibility to "disable" a chosen select, the same way we set attribute disabled="disabled" in standard select elements.

**Comment by NKjoep** [comment]
I've sent a pull request for this...

Here's a simple function I've pushed
https://github.com/NKjoep/chosen/commit/ec99b01210cd74bc8340a523adeef2cc9b451dec

**Comment by RiZKiT** [comment]
The pull request got pulled, so you may close this one?

**Comment by NKjoep** [comment]
Thank you!
